// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"accountsapi/accounts/internal/biz"
	"accountsapi/accounts/internal/conf"
	"accountsapi/accounts/internal/data"
	"accountsapi/accounts/internal/server"
	"accountsapi/accounts/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	accountsRepo := data.NewAccountsRepo(dataData, logger)
	accountsUseCase := biz.NewAccountsUseCase(accountsRepo, logger)
	transactionRepo := data.NewTransactionRepo(dataData, logger)
	transactionUseCase := biz.NewTransactionUseCase(transactionRepo, accountsRepo, logger)
	accountsService := service.NewAccountsService(accountsUseCase, transactionUseCase)
	grpcServer := server.NewGRPCServer(confServer, accountsService, logger)
	httpServer := server.NewHTTPServer(confServer, accountsService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
