// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package accounts

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// Set the error code separately for an enumeration.
func IsAccountExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ACCOUNT_EXISTS.String() && e.Code == 400
}

// Set the error code separately for an enumeration.
func ErrorAccountExists(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_ACCOUNT_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsAccountNotExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ACCOUNT_NOT_EXIST.String() && e.Code == 404
}

func ErrorAccountNotExist(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_ACCOUNT_NOT_EXIST.String(), fmt.Sprintf(format, args...))
}
